{
 "title": "api",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "График среднего времени выполнения запроса (симуляция)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(company_details_query_duration_seconds_sum[1m]) \r\n/ \r\nrate(company_details_query_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95-й перцентиль времени выполнения SQL-запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_db_query_duration_seconds_bucket[1m])) by (le, query_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95-й перцентиль времени отклика по endpoint'ам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, endpoint) (rate(service_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду за последнюю минуту, сгруппированные по endpoint'ам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(service_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}