{
 "title": "postgres",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Кол-во блокировок",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_locks_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Буферы, выделенные бекграундом",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_bgwriter_buffers_alloc_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Индексные сканы\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "pg_stat_user_tables_idx_scan", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Последовательные сканы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "pg_stat_user_tables_seq_scan", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Кол-во удалений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "pg_stat_user_tables_n_tup_del", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Кол-во обновлений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "pg_stat_user_tables_n_tup_upd", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Кол-во вставок в таблицы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "pg_stat_user_tables_n_tup_ins", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Размер БД",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Кол-во активных подключений к БД",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "pg_stat_activity_count", "legendFormat": "__auto" }
   ]
  }
 ]
}